/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/earth.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Cube001_Cube004-Mesh"].geometry}
        material={materials.Red}
       
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Cube001_Cube004-Mesh_1"].geometry}
        material={nodes["Cube001_Cube004-Mesh_1"].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Cube003.geometry}
        material={materials.LightBrown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere004_Icosphere005.geometry}
        material={nodes.Icosphere004_Icosphere005.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere003_Icosphere004.geometry}
        material={nodes.Icosphere003_Icosphere004.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere002_Icosphere003.geometry}
        material={nodes.Icosphere002_Icosphere003.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere001_Icosphere002.geometry}
        material={nodes.Icosphere001_Icosphere002.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Icosphere-Mesh"].geometry}
        material={materials.Blue}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Icosphere-Mesh_1"].geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Icosphere-Mesh_2"].geometry}
        material={materials.Snow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Icosphere-Mesh_3"].geometry}
        material={materials.Brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Icosphere-Mesh_4"].geometry}
        material={materials.DarkGreen}
      />
    </group>
  );
}

useGLTF.preload("/earth.gltf");
